# Generated by Django 5.2.4 on 2025-07-13 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddits', '0003_subreddit_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='post_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('moderator_notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='subreddits.subreddit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subreddit', 'owner'], name='posts_post_subredd_af0feb_idx'), models.Index(fields=['-vote_count'], name='posts_post_vote_co_c5e6db_idx')],
            },
        ),
    ]
