# Generated by Django 5.2.4 on 2025-07-13 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rule',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='subreddits.subreddit'),
        ),
    ]
