# Generated by Django 5.2.4 on 2025-07-13 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
